language: erlang
otp_release:
  - 18.3
  - 19.3
  - 20.0
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
  - export PATH=$PATH:$PWD
script:
  - make ci
notifications:
  email: false
